trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Instalar Java 11'

- script: mvn clean verify -DskipTests
  displayName: 'Ejecutar automatización con Maven'