webdriver.driver=chrome
webdriver.chrome.driver=C:/chrome-testing/chromedriver-win64/chromedriver.exe
chrome.binary=C:/chrome-testing/chrome-win64/chrome.exe
serenity.browser.visible=true
serenity.browser.maximized=true


